# Default preset for failure modes analysis
repo_path: "."
scope:
  - "."
time_budget_minutes: 60
depth: normal
output_format: markdown
risk_tolerance: conservative
audience: senior_eng
failure_categories:
  - runtime
  - data
  - network
  - resource
